import { z } from 'zod';

const dateInput = z
  .string()
  .datetime({ offset: true })
  .or(z.string().regex(/^\d{4}-\d{2}-\d{2}$/));

// iana timezone names are up to ~40 chars in practice. we validate shape loosely
// and let the backend reject unknown zones when constructing Intl.DateTimeFormat.
const tzInput = z.string().min(1).max(64);

// query shape for GET /rooms/:id/report. from/to are inclusive bounds; when given a
// bare yyyy-mm-dd the server interprets it as the full day in the requested tz so the
// frontend's "last 30 days" actually matches the user's local calendar. userId narrows
// the report to a single member without changing the summary structure.
export const reportQuerySchema = z
  .object({
    from: dateInput,
    to: dateInput,
    userId: z.string().min(1).optional(),
    tz: tzInput.optional(),
    format: z.enum(['json', 'pdf']).optional().default('json'),
  })
  .refine((v) => new Date(v.from) <= new Date(v.to), {
    message: '"from" must be on or before "to"',
    path: ['to'],
  });

export type ReportQuery = z.infer<typeof reportQuerySchema>;

// body for POST /rooms/:id/report/ai-summary — same filter shape as the report query
// so the server can regenerate the underlying report if the client didn't pass one.
export const aiSummaryRequestSchema = z.object({
  from: dateInput,
  to: dateInput,
  userId: z.string().min(1).optional(),
  tz: tzInput.optional(),
});
export type AiSummaryRequest = z.infer<typeof aiSummaryRequestSchema>;

export interface AiSummaryResponse {
  narrative: string;
  // whether the narrative actually came from an llm. false means we fell back to the
  // deterministic builder because ai was disabled or unreachable. the ui can decide
  // whether to still show a "enhanced with ai" label.
  aiGenerated: boolean;
}

// /users/me/daily-recap response — a calm at-a-glance block for the dashboard.
// the `insights` array is a short list of bullet-style observations generated by
// the basic insight engine: busiest day, heaviest task, tracking gap, etc.
export interface DailyRecapResponse {
  date: string; // yyyy-mm-dd in the user's tz
  tz: string;
  totalDuration: number;
  sessionCount: number;
  completedTaskCount: number;
  sessions: Array<{
    id: string;
    roomId: string;
    roomName: string;
    intent: string;
    summary: string | null;
    duration: number;
    linkedTaskTitle: string | null;
  }>;
  completedTasks: Array<{
    id: string;
    roomId: string;
    roomName: string;
    title: string;
  }>;
  narrative: string;
  insights: string[];
  aiGenerated: boolean;
  generatedAt: string;
}

// suggested summary body for POST /sessions/active/suggest-summary
export const suggestSessionSummarySchema = z.object({
  // optional override so the frontend can request a suggestion using the currently
  // elapsed time without waiting for stopSession to finalise duration.
  elapsedMs: z.number().int().nonnegative().optional(),
});
export type SuggestSessionSummaryInput = z.infer<typeof suggestSessionSummarySchema>;

export interface SuggestSessionSummaryResponse {
  suggestion: string;
  aiGenerated: boolean;
}
